language: java
jdk:
  - oraclejdk8
before_install:
  - git config --global user.email "travis-ci@mikroskeem.eu"
  - git config --global user.name "Travis CI"
script:
  - echo "Pass"
cache:
  directories:
    - '$HOME/.m2/repository'
